#ifndef DATAMANAGEMENTSYSTEM_GLOBAL_H
#define DATAMANAGEMENTSYSTEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAMANAGEMENTSYSTEM_LIBRARY)
#  define DATAMANAGEMENTSYSTEMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAMANAGEMENTSYSTEMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAMANAGEMENTSYSTEM_GLOBAL_H
